name: Node.js CI

on:
  push:
    branches: [ master]
  issues:
    type: [ opened ]
jobs:
  build:

    runs-on: ubuntu-lastest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version:${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
  
